### PR TITLE
Release 0.1.1

### PR DESCRIPTION
**Pull request by Vayel**

### CODE REVIEW

**Comment by Vayel** [comment]
@MaxHalford the tag worked actually, but not the deployment on Pypi (see Travis logs).

**Comment by MaxHalford** [comment]
It's okay I'm handling it. Also the next version is `0.0.2`, not `0.1.1` because there's no API change.

**Comment by Vayel** [comment]
Can you edit the `__version__.py` and the changelog?

One weird thing is that the docs didn't build even if it's supposed to be run before the deployment on Pypi.

**Comment by Vayel** [comment]
@MaxHalford how can we merge the `v0.0.2` tag into `master`?

**Comment by MaxHalford** [comment]
Ok it's all good!

**Pull request closed without merging**
